# このファイルはコミット前にコード品質を自動チェックします（ruff/black/mypy）
repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.5.7
    hooks:
      - id: ruff
        args: ["--fix"]  # 自動修正可能なものは修正
      - id: ruff-format

  - repo: https://github.com/psf/black
    rev: 24.8.0
    hooks:
      - id: black

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.10.0
    hooks:
      - id: mypy
        files: ^bot/
        additional_dependencies: []

  - repo: local
    hooks:
      - id: progress-snapshot
        name: progress-snapshot  # これは何をするフック？→ コミット完了後に進行状況を docs/progress.md へ追記する
        entry: python -m bot.tools.progress_logger
        language: system
        stages: [post-commit]
        pass_filenames: false
